final List<Map<String, String>> items = [
    //등
    {
      'title': '랫 풀 다운',
      'subtitle': '등, 이두',
      'image': 'assets/back/lat-pulldown.png',
      'gif':'assets/back/lat-pulldown.gif',
      'tip': """랫 풀 다운은 등 상부 근육에 집중적으로 작용하여 세밀한 근육 발달을 위해 효과적입니다. 자세 교정과 근력 향상에 도움이 됩니다""",
      'preparation': """랫 풀 다운 머신 앞에 앉아 손잡이에 손을 넓게 잡아주세요
몸을 뒤로 젖혀 앉고, 발은 바닥에 고정하세요
팔을 완전히 뻗은 상태에서 시작합니다""",
      'movement':"""손잡이를 천천히 아래로 당겨오면서 숨을 내쉽니다
단단히 고정된 상체와 팔의 움직임으로 손잡이를 가슴이나 목 아래까지 당겨 올라가주세요
상체를 움직이지 않으면서 팔만 움직여 원 위치로 손잡이를 천천히 올려주며, 이때 숨을 들이쉽니다""",
      'breathing':"""손잡이를 당겨올릴 때 숨을 내쉬며, 원래 위치로 도아올 때 숨을 들이쉬세요""",
      'precautions': """적절한 중량을 선택하세요.
운동 중 불편함을 느끼면 즉시 중단하세요
상체를 고정하고 팔만 움직이세요""",
      'category': '등',
    },
    {
      'title': '원 암 랫 풀 다운',
      'subtitle': '등, 이두',
      'image': 'assets/back/one-arm-lat-pulldown.png',
      'gif':'assets/back/one-arm-lat-pulldown.gif',
      'tip':"""한 팔로 랫 풀 다운을 진행하여 광배근을 타겟하는 운동입니다""",
      'preparation': """무릎이 조이지 않도록 무릎 패드 높이를 조절해 주세요
그립을 잡고 날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
앞쪽을 보고 있는 손바닥을 몸쪽으로 돌리면서 어깨 위치까지 당겨주세요
다시 손바닥이 앞쪽을 향하도록 돌리면서 팔을 올려주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """어깨와 팔을 완전히 펴면 어깨에 무리가 갈 수 있으니 주의해 주세요
승모근이 따라 올라가지 않도록 주의해 주세요
팔꿈치가 뒤로 빠지지 않도록 주의해 주세요""",
      'category': '등',
    },
    {
      'title': '클로즈 그립 랫 풀 다운',
      'subtitle': '등, 어깨',
      'image': 'assets/back/close-grip-lat-pulldown.png',
      'gif': 'assets/back/close-grip-lat-pulldown.gif',
      'tip':"""클로즈 그립을 사용함에 따라 등근육 아래까지 자극을 가져갈 수 있어요. 쇄골에 바를 붙여주는 동작으로 진행해주세요""",
      'preparation': """무릎이 조이지 않도록 무릎 패드 높이를 조절해 주세요
손바닥이 앞으로 가게 해서 어깨너비보다 조금 좁게 바를 잡아주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""팔꿈치가 앞을 향한 상태에서 팔꿈치를 아래로 내려주세요
바가 쇄골에 닿을 때까지 당겨주세요
천천히 팔을 올리면서 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """어깨와 팔을 완전히 펴면 어깨에 무리가 갈 수 있으니 주의해 주세요
승모근이 따라 올라가지 않도록 주의해 주세요""",
      'category': '등',
    },

    {
      'title': '케이블 스트레이트 암 풀 다운',
      'subtitle': '등, 어깨',
      'image': 'assets/back/cable-straight-arm-pulldown.png',
      'gif': 'assets/back/cable-straight-arm-pulldown.gif',
      'tip':"""팔을 살짝 구분릴 채로 유지하면서 몸에 닿을 때까지 당겨주세요. 이때, 가슴을 들어주면 자극을 더 느끼실 수 있습니다""",
      'preparation': """로프를 눈높이에 맞춰 주세요
어깨너비로 로프를 잡아주세요
팔을 쭉 펴고, 수직이 되는 위치에 서주세요""",
      'movement':"""겨드랑이에 힘을 주고 로프가 몸쪽으로 오도록 당겨주세요
어깨 위치까지 천천히 다시 올려주세요""",
      'breathing':"""팔을 내릴 때 숨을 내쉬고, 팔을 올릴 때 숨을 들이쉬세요""",
      'precautions': """팔이 굽어지지 않도록 주의해 주세요
팔이 어깨보다 높이 올라가지 않도록 주의해 주세요
승모근이 올라가지 않도록 주의해 주세요""",
      'category': '등',
    },

    {
      'title': '풀 업',
      'subtitle': '등, 이두',
      'image': 'assets/back/pull-up.png',
      'gif': 'assets/back/pull-up.gif',
      'tip':"""풀 업은 팔을 당겨서 상체가 올리는 동작이고, 그립을 잡는 방식에 따라 손바닥이 바깥쪽을 향하면 풀업, 안쪽을 향하면 친업이라고 해요""",
      'preparation': """어깨너비보다 조금 넓게 바를 잡아주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },
    {
      'title': '중량 풀업',
      'subtitle': '등, 이두',
      'image': 'assets/back/weighted-pull-up.png',
      'gif': 'assets/back/weighted-pull-up.png',
      'tip':"""풀업이 너무 쉽게 느껴지시는 분들에게 추천드려요. 부상에 유의하며 가슴이 바에 닿도록 올라가주세요""",
      'preparation': """본인에게 맞는 무게를 허리를 매주세요
어깨너비보다 조금 넓게 바를 잡아주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },
    {
      'title': '어시스티드 머신 풀업',
      'subtitle': '등, 이두',
      'image': 'assets/back/assisted-pull-up.png',
      'gif': 'assets/back/assisted-pull-up.gif',
      'tip':"""어시스트 머신을 이용하기 때문에 맨몸 풀 업이 힘든 분들에게 도움이 될 수 있어요. 10개 할 수 있을 정도의 중량을 설정한 후에 조금씩 늘려가주세요""",
      'preparation': """도움받을 무게로 세팅해 주세요
어깨너비보다 조금 넓게 바를 잡고, 패드 위에 무릎을 꿇어주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""몸이 올라갈 때 숨을 내쉬고, 몸이 내려갈 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },
    {
      'title': '밴드 풀 업',
      'subtitle': '등, 이두',
      'image': 'assets/back/band-pull-up.png',
      'gif': 'assets/back/band-pull-up.gif',
      'tip':"""밴드를 발에 끼우는 것부터 시작해서 차근차근 무릎으로 옮겨 난이도를 올려주세요. 너무 빠르게 하지 않도록 주의해주세요""",
      'preparation': """도움받을 밴드를 바에 묶어주세요
어깨너비보다 조금 넓게 바를 잡고, 밴드 위에 올라서 주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },

    {
      'title': '친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/chin-up.png',
      'gif': 'assets/back/chin-up.gif',
      'tip':"""친 업은 등 근육과 이두 근육의 힘으로 상체를 위로 올리는 동작이에요. 손잡이를 잡는 방식에 따라 손바닥이 바깥쪽을 향하면 풀 업, 안쪽을 향하면 친 업이라고 해요. 등의 두께를 두껍게 만들기에 좋은 운동이에요""",
      'preparation': """손바닥이 몸을 향하게 바를 잡아주세요
그립의 넓이는 어깨너비로 잡아주세요
어깨가 굽지 않게 가슴을 열어주세요""",
      'movement':"""가슴이 바를 향하도록 팔에 힘을 주어 올라가세요
천천히 시작 자세로 돌아오세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """반동 때문에 몸이 흔들리지 않도록 천천히 동작을 진행해주세요""",
      'category': '등',
    },
    {
      'title': '중량 친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/weighted-chin-up.png',
      'gif': 'assets/back/weighted-chin-up.gif',
      'tip':"""친업이 너무 쉽게 느껴지시는 분들에게 추천드려요. 부상에 유의하며 가슴이 바에 닿도록 올라가주세요""",
      'preparation': """본인에게 맞는 무게를 허리에 매주세요
어깨너비로 바를 잡아주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },
    {
      'title': '밴드 친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/band-chin-up.png',
      'gif': 'assets/back/band-chin-up.gif',
      'tip':"""밴드를 발에 끼우는 것부터 시작해서 차근차근 무릎으로 옮겨 난이도를 올려주세요. 너무 빠르게 하지 않도록 주의해주세요""",
      'preparation': """도움받을 밴드를 바에 묶어주세요
어깨너비로 바를 잡고, 밴드 위에 올라서 주세요
날개뼈를 모아 가슴을 펴주세요""",
      'movement':"""가슴이 바에 닿도록 팔을 당겨주세요
날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
가슴을 편 상태로 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """내려왔을 때 시작 자세가 풀리지 않도록 주의해 주세요
팔이 아닌 날개뼈를 움직이는 힘으로 올라가 주세요""",
      'category': '등',
    },

    {
      'title': '케이블 시티드 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/cable-seated-row.png',
      'gif': 'assets/back/cable-seated-row.gif',
      'tip':"""등 근육 안쪽을 키우기 좋은 운동이에요. 팔의 힘이 아닌 어깨를 뒤로 보낸후 등의 힘으로 당겨주세요""",
      'preparation': """무릎이 살짝 굽혀지는 위치에 앉아주세요
다리를 고정하고 그립을 잡아주세요
허리를 세우고, 가슴을 펴주세요""",
      'movement':"""날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
그립이 배에 닿도록 당겨주세요
허리를 세운 상태로 팔꿈치를 완전히 펴면서 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치를 벌어지지 않도록 주의해 주세요
허리가 말리지 않도록 가슴을 펴주세요
허리가 앞뒤로 움직이지 않도록 고정해 주세요""",
      'category': '등',
    },
    {
      'title': '바벨 로우(벤트 오버 바벨 로우)',
      'subtitle': '등, 이두',
      'image': 'assets/back/barbell-row.png',
      'gif': 'assets/back/barbell-row.gif',
      'tip':"""바벨을 잡는 각도, 넓이 그리고 수행하는 동작의 범위에 따라 다양한 명칭으로 불리는 운동이에요. 완벽한 등근육을 위한 최고의 운동이에요""",
      'preparation': """바벨이 정강이에 위치할 수 있게 높이를 조절해 주세요
다리는 어깨너비만큼 벌려 주세요
엉덩이를 뒤로 살짝 빼면서 자연스럽게 무릎을 굽혀 주세요
어깨너비만큼 바벨을 잡고 가슴을 펴주세요""",
      'movement':"""바벨이 수직으로 올라갈 수 있게 배꼽 쪽으로 당겨주세요
날개뼈를 모으면서 자연스럽게 팔꿈치와 손을 당겨주세요
무게를 등의 힘으로 버티며 무릎 아래까지 손을 내려주세요""",
      'breathing':"""팔을 올릴 때 숨을 내쉬고, 팔을 내릴 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치가 벌어지지 않도록 주의해 주세요
허리가 너무 세워지거나 위아래로 움직이지 않도록 주의해 주세요
허리가 말리지 않도록 코어에 힘을 주세요""",
      'category': '등',
    },
    {
      'title': '펜들레이 로우',
      'subtitle': '등',
      'image': 'assets/back/pendlay-row.png',
      'gif': 'assets/back/pendlay-row.gif',
      'tip':"""바벨을 땅에 내려놓은 상태에서 허리를 숙이고 들어 올리는 운동으로 후면 근육 발달에 좋은 운동이에요""",
      'preparation': """바벨과 3cm 떨어진 곳에 정강이를 위치시켜 주세요
다리는 어깨너비만큼 벌려 주세요
엉덩이를 뒤로 살짝 빼면서 자연스럽게 무릎을 굽혀 주세요
어깨너비만큼 바벨을 잡고 가슴을 펴주세요""",
      'movement':"""바벨과 3cm 떨어진 곳에 정강이를 위치시켜 주세요
다리는 어깨너비만큼 벌려 주세요
엉덩이를 뒤로 살짝 빼면서 자연스럽게 무릎을 굽혀 주세요
어깨너비만큼 바벨을 잡고 가슴을 펴주세요""",
      'breathing':"""바벨을 올릴 때 숨을 내쉬고, 바벨을 내릴 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치가 벌어지지 않도록 주의해 주세요
허리가 너무 세워지거나 위아래로 움직이지 않도록 주의해 주세요
허리가 말리지 않도록 코어에 힘을 주세요""",
      'category': '등',
    },
    {
      'title': '티 바 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/t-bar-row.png',
      'gif': 'assets/back/t-bar-row.gif',
      'tip':"""티바 로우는 등의 라인을 집중적으로 자극할 수 있음은 물론, 평형 유지가 쉽기에 초보자가 도전하기 좋은 운동입니다""",
      'preparation': """티바 머신에 서서 발은 어깨 너비로 벌리고, 로우 바에 양손을 잡아주세요
세운 상태에서 약간 골반을 뒤로 빼고 허리를 앞으로 숙이며 상체를 약 45도 각도로 들어주세요
이때, 등과 팔은 뻗은 상태로 유지하고, 머리도 자연스럽게 뻗어주세요""",
      'movement':"""팔꿈치를 구부린 채로 로우 바를 몸쪽으로 당겨오면서 숨을 내쉽니다
가슴에 바를 닿게 하여 등 근육을 최대한 수축시키세요
최상단에서 잠시 멈춘 후, 천천히 원래 위치로 돌아가면서 숨을 들이쉽니다""",
      'breathing':"""바를 몸쪽으로 당길 때 숨을 내쉬고, 원래 위치로 돌아올 때 숨을 들이쉬세요""",
      'precautions': """등 또는 어깨에 통증이 느껴지면 즉시 운동을 중단하세요
허리를 너무 굽히지 않도록 주의해야 합니다
과도한 중량을 사용하지 않도록 주의해주세요""",
      'category': '등',
    },
    {
      'title': '인버티드 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/inverted-row.png',
      'gif': 'assets/back/inverted-row.gif',
      'tip':"""인버티드 로우는 풀 업의 보조운동으로 많이 하는 운동이에요. 조금 힘들어도 완벽한 자세로 호흡 신경쓰면서 해주면 아주 좋아요""",
      'preparation': """스미스머신의 바를 골반 위치에 걸어주세요
바가 낮아질수록 운동 강도가 높아집니다
하늘을 본 상태에서 어깨너비보다 조금 넓게 바를 잡아주세요
다리를 펴고, 몸을 일직선으로 만들어 주세요""",
      'movement':"""날개뼈를 모으면서 자연스럽게 팔을 당겨주세요
팔꿈치가 수직이 될 때까지 당겨주세요
몸을 일직선으로 유지한 채로 팔을 천천히 펴면서 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """스미스머신의 바가 풀리지 않도록 주의해 주세요""",
      'category': '등',
    },

    {
      'title': '덤벨 로우(벤트 오버 덤벨 로우)',
      'subtitle': '등, 이두',
      'image': 'assets/back/dumbbell-row.png',
      'gif': 'assets/back/dumbbell-row.gif',
      'tip':"""덤벨은 바벨보다 움직일 수 있는 범위가 넓기 때문에 근신경 발달에 효과적이고 등근육을 멋지게 만들 수 있어요""",
      'preparation': """정강이에 위치에서 어깨너비로 덤벨을 잡아주세요
다리는 어깨너비만큼 벌려 주세요
엉덩이를 뒤로 살짝 빼면서 자연스럽게 무릎을 굽혀 주세요""",
      'movement':"""덤벨이 수직으로 올라갈 수 있게 옆구리 쪽으로 당겨주세요
날개뼈를 모으면서 자연스럽게 팔꿈치와 손을 당겨주세요
등의 힘으로 버티며 무릎 아래까지 손을 내려주세요""",
      'breathing':"""팔을 당길 때 숨을 내쉬고, 팔을 펼 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치가 벌어지지 않도록 주의해 주세요
허리가 너무 세워지거나 위아래로 움직이지 않도록 주의해 주세요
허리가 말리지 않도록 코어에 힘을 주세요""",
      'category': '등',
    },
    {
      'title': '원 암 덤벨 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/one-arm-dumbbell-row.png',
      'gif': 'assets/back/one-arm-dumbbell-row.gif',
      'tip':"""덤벨 하나만 있으면 어디서나 할 수 있는 등운동이에요. 등 전체를 훈련하는 동작이에요""",
      'preparation': """덤벨을 든 팔의 반대쪽 무릎을 벤치에 올려주세요
덤벨을 들지 않은 팔은 쭉펴서 상체를 지지해 주세요
상체와 벤치가 평행하도록 자세를 잡고, 가슴을 펴주세요""",
      'movement':"""덤벨을 든 팔을 당겨주세요
팔꿈치를 옆구리에 붙이고, 팔꿈치가 수직이 될 때까지 당겨주세요
팔꿈치가 완전히 펴질 때까지 천천히 내리면서 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 올릴 때 숨을 내쉬고, 팔을 내릴 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치가 벌어지지 않도록 주의해 주세요
허리가 말리지 않도록 가슴을 펴주세요""",
      'category': '등',
    },
    {
      'title': '덤벨 리어 델트 로우',
      'subtitle': '등, 어깨',
      'image': 'assets/back/dumbbell-rear-delt-row.png',
      'gif': 'assets/back/dumbbell-rear-delt-row.gif',
      'tip':"""덤벨 하나만 있으면 어디서나 할 수 있는 등운동이에요. 등 전체를 훈련하는 동작이에요""",
      'preparation': """덤벨을 든 팔의 반대쪽 무릎을 벤치에 올려주세요
덤벨을 들지 않은 팔은 쭉펴서 상체를 지지해 주세요
상체와 벤치가 평행하도록 자세를 잡고, 가슴을 펴주세요""",
      'movement':"""덤벨을 든 팔을 당겨주세요
팔꿈치를 옆구리에 붙이고, 팔꿈치가 수직이 될 때까지 당겨주세요
팔꿈치가 완전히 펴질 때까지 천천히 내리면서 시작 자세로 돌아와 주세요""",
      'breathing':"""팔을 올릴 때 숨을 내쉬고, 팔을 내릴 때 숨을 들이쉬세요""",
      'precautions': """팔꿈치가 벌어지지 않도록 주의해 주세요
허리가 말리지 않도록 가슴을 펴주세요""",
      'category': '등',
    },

    {
      'title': '백 익스텐션',
      'subtitle': '등, 둔근',
      'image': 'assets/back/back-extension.png',
      'gif': 'assets/back/back-extension.gif',
      'tip':"""허리, 엉덩이 그리고 허벅지 뒤까지 발달 시킬 수 있는 아주 좋은 운동이에요. 허리가 약하거나, 디스크 증상으로 고생을 하는 사람들에게 정말 좋은 운동이에요""",
      'preparation': """몸통 패드가 고관절에 닿을 수 있도록 위치를 조절해 주세요
발이 움직이지 않도록 발목을 패드에 붙여주세요""",
      'movement':"""가슴을 편 상태로 고관절을 굽히며 내려가 주세요
      코어에 힘을 주고 고관절을 펴면서 올라와 주세요""",
      'breathing':"""상체를 내릴 때 숨을 들이쉬고, 상체를 올릴 때 숨을 내쉬세요""",
      'precautions': """운동하는 내내 코어에 힘이 풀리지 않도록 주의해 주세요
허리가 말리지 않도록 가슴을 펴주세요""",
      'category': '등',
    },

    //가슴
    {
      'title': '바벨 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-bench-press.png',
      'gif': 'assets/chest/barbell-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '바벨 인클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-incline-bench-press.png',
      'gif': 'assets/chest/barbell-incline-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '바벨 디클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-decline-bench-press.png',
      'gif': 'assets/chest/barbell-decline-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '덤벨 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-bench-press.png',
      'gif': 'assets/chest/dumbbell-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,      
      'category': '가슴',
    },
    {
      'title': '덤벨 인클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-incline-bench-press.png',
      'gif': 'assets/chest/dumbbell-incline-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '머신 체스트 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/machine-chest-press.png',
      'gif': 'assets/chest/machine-chest-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '랜드마인 체스트 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/landmine-chest-press.png',
      'gif': 'assets/chest/landmine-chest-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '덤벨 헥스 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/dumbbell-hex-press.png',
      'gif': 'assets/chest/dumbbell-hex-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '스벤드 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/svend-press.png',
      'gif': 'assets/chest/svend-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '케이블 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-fly.png',
      'gif': 'assets/chest/cable-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '케이블 하이 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-high-fly.png',
      'gif': 'assets/chest/cable-high-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '케이블 로우 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-low-fly.png',
      'gif': 'assets/chest/cable-low-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '케이블 인클라인 벤치 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/incline-cable-fly.png',
      'gif': 'assets/chest/incline-cable-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '케이블 디클라인 벤치 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/decline-cable-fly.png',
      'gif': 'assets/chest/decline-cable-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '푸시 업',
      'subtitle': '가슴, 어깨, 삼두',
      'image': 'assets/chest/push-up.png',
      'gif': 'assets/chest/push-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '중량 푸시 업',
      'subtitle': '가슴, 어깨, 삼두',
      'image': 'assets/chest/weighted-push-up.png',
      'gif': 'assets/chest/weighted-push-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '바벨 풀 오버',
      'subtitle': '가슴, 등',
      'image': 'assets/chest/barbell-pullover.png',
      'gif': 'assets/chest/barbell-pullover.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    {
      'title': '덤벨 풀 오버',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-pullover.png',
      'gif': 'assets/chest/dumbbell-pullover.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '팩 덱 플라이(머신 플라이)',
      'subtitle': '가슴',
      'image': 'assets/chest/pec-deck-fly.png',
      'gif': 'assets/chest/pec-deck-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },

    {
      'title': '체스트 딥스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/chest-dip.png',
      'gif': 'assets/chest/chest-dip.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '가슴',
    },
    
    //어깨
    {
      'title': '바벨 숄더 프레스(밀리터리 프레스, 오버헤드 프레스)',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/military-press.png',
      'gif': 'assets/shoulder/military-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '덤벨 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/dumbbell-front-raise.png',
      'gif': 'assets/shoulder/dumbbell-front-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/cable-front-raise.png',
      'gif': 'assets/shoulder/cable-front-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '플레이트 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/plate-front-raise.png',
      'gif': 'assets/shoulder/plate-front-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '아놀드 덤벨 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/arnold-press.png',
      'gif': 'assets/shoulder/arnold-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '시티드 덤벨 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/dumbbell-shoulder-press.png',
      'gif': 'assets/shoulder/dumbbell-shoulder-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '머신 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/machine-shoulder-press.png',
      'gif': 'assets/shoulder/machine-shoulder-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/cable-shoulder-press.png',
      'gif': 'assets/shoulder/cable-shoulder-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 업라이트 로우',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/cable-upright-row.png',
      'gif': 'assets/shoulder/cable-upright-row.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '바벨 업라이트 로우',
      'subtitle': '어깨, 승모',
      'image': 'assets/shoulder/barbell-upright-row.png',
      'gif': 'assets/shoulder/barbell-upright-row.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    

    {
      'title': '덤벨 레터럴 레이즈(사이드 레터럴 레이즈)',
      'subtitle': '어깨',
      'image': 'assets/shoulder/dumbbell-lateral-raise.png',
      'gif': 'assets/shoulder/dumbbell-lateral-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '머신 레터럴 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/machine-lateral-raise.png',
      'gif': 'assets/shoulder/machine-lateral-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 레터럴 레이즈',
      'subtitle': '어깨, 전완',
      'image': 'assets/shoulder/cable-lateral-raise.png',
      'gif': 'assets/shoulder/cable-lateral-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '덤벨 인클라인 Y 레이즈',
      'subtitle': '어깨, 승모',
      'image': 'assets/shoulder/dumbbell-incline-y-raise.png',
      'gif': 'assets/shoulder/dumbbell-incline-y-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 Y 레이즈',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/cable-y-raise.png',
      'gif': 'assets/shoulder/cable-y-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    

    {
      'title': '덤벨 리어 델트 레이즈(벤트 오버 레터럴 레이즈)',
      'subtitle': '어깨, 등',
      'image': 'assets/shoulder/dumbbell-rear-delt-raise.png',
      'gif': 'assets/shoulder/dumbbell-rear-delt-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '머신 리버스 플라이(팩 덱 리어 델트, 머신 리어 델트 플라이)',
      'subtitle': '어깨, 등',
      'image': 'assets/shoulder/machine-reverse-fly.png',
      'gif': 'assets/shoulder/machine-reverse-fly.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '케이블 페이스 풀',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/cable-face-pull.png',
      'gif': 'assets/shoulder/cable-face-pull.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },
    {
      'title': '밴드 페이스 풀',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/banded-face-pull.png',
      'gif': 'assets/shoulder/banded-face-pull.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },

    {
      'title': '클린 앤 저크',
      'subtitle': '어깨, 대퇴사두',
      'image': 'assets/shoulder/clean-and-jerk.png',
      'gif': 'assets/shoulder/clean-and-jerk.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '어깨',
    },

    //삼두
    {
      'title': '클로즈 그립 벤치 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/close-grip-bench-press.png',
      'gif': 'assets/triceps/close-grip-bench-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '클로즈 그립 덤벨 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/close-grip-dumbbell-press.png',
      'gif': 'assets/triceps/close-grip-dumbbell-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '덤벨 테이트 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/dumbbell-tate-press.png',
      'gif': 'assets/triceps/dumbbell-tate-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/tricep-dips.png',
      'gif': 'assets/triceps/tricep-dips.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '중량 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/weighted-dips.png',
      'gif': 'assets/triceps/weighted-dips.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '머신 어시스티드 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/machine-assisted-dips.png',
      'gif': 'assets/triceps/machine-assisted-dips.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '벤치 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/bench-dips.png',
      'gif': 'assets/triceps/bench-dips.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '덤벨 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/dumbbell-tricep-extension.png',
      'gif': 'assets/triceps/dumbbell-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '원 암 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/one-arm-tricep-extension.png',
      'gif': 'assets/triceps/one-arm-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '덤벨 라잉 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/dumbbell-lying-tricep-extension.png',
      'gif': 'assets/triceps/dumbbell-lying-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '머신 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/machine-tricep-extension.png',
      'gif': 'assets/triceps/machine-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '바벨 라잉 트라이셉 익스텐션(스컬크러셔)',
      'subtitle': '삼두, 전완',
      'image': 'assets/triceps/barbell-lying-tricep-extension.png',
      'gif': 'assets/triceps/barbell-lying-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '바벨 인클라인 트라이셉 익스텐션(스컬크러셔)',
      'subtitle': '삼두',
      'image': 'assets/triceps/barbell-incline-tricep-extension.png',
      'gif': 'assets/triceps/barbell-incline-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '케이블 오버헤드 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-overhead-tricep-extension.png',
      'gif': 'assets/triceps/cable-overhead-tricep-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '케이블 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-tricep-pushdown.png',
      'gif': 'assets/triceps/cable-tricep-pushdown.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '케이블 로프 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-rope-tricep-pushdown.png',
      'gif': 'assets/triceps/cable-rope-tricep-pushdown.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '케이블 리버스그립 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-reverse-grip-pushdown.png',
      'gif': 'assets/triceps/cable-reverse-grip-pushdown.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '케이블 V바 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/v-bar-tricep-pushdown.png',
      'gif': 'assets/triceps/v-bar-tricep-pushdown.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },

    {
      'title': '덤벨 트라이셉 킥 백',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/dumbbell-tricep-kickback.png',
      'gif': 'assets/triceps/dumbbell-tricep-kickback.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    {
      'title': '케이블 트라이셉 킥 백',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-tricep-kickback.png',
      'gif': 'assets/triceps/cable-tricep-kickback.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '삼두',
    },
    
    //이두
    {
      'title': '컨센트레이션 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/concentration-curl.png',
      'gif': 'assets/biceps/concentration-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤벨 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-biceps-curl.png',
      'gif': 'assets/biceps/dumbbell-biceps-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤벨 해머 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/hammer-curl.png',
      'gif': 'assets/biceps/hammer-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤벨 인클라인 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-incline-curl.png',
      'gif': 'assets/biceps/dumbbell-incline-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤벨 인클라인 해머 컬',
      'subtitle': '이두',
      'image': 'assets/biceps/dumbbell-incline-hammer-curl.png',
      'gif': 'assets/biceps/dumbbell-incline-hammer-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤벨 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-preacher-curl.png',
      'gif': 'assets/biceps/dumbbell-preacher-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '덤밸 조트맨 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/zottman-curl.png',
      'gif': 'assets/biceps/zottman-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },

    {
      'title': '바벨 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-curl.png',
      'gif': 'assets/biceps/barbell-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '바벨 클로즈 그립 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-close-grip-curl.png',
      'gif': 'assets/biceps/barbell-close-grip-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '바벨 리버스 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-reverse-curl.png',
      'gif': 'assets/biceps/barbell-reverse-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '바벨 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-preacher-curl.png',
      'gif': 'assets/biceps/barbell-preacher-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '바벨 드래그 컬',
      'subtitle': '이두, 어깨',
      'image': 'assets/biceps/drag-curl.png',
      'gif': 'assets/biceps/drag-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '스파이더 바벨 컬',
      'subtitle': '이두, 어깨',
      'image': 'assets/biceps/spider-barbell-curl.png',
      'gif': 'assets/biceps/spider-barbell-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },

    {
      'title': '이지 바 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-bicep-curl.png',
      'gif': 'assets/biceps/ez-bar-bicep-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '이지 바 리버스 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-reverse-curl.png',
      'gif': 'assets/biceps/ez-bar-reverse-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '이지 바 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-preacher-curl.png',
      'gif': 'assets/biceps/ez-bar-preacher-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },

    {
      'title': '케이블 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-bicep-curl.png',
      'gif': 'assets/biceps/cable-bicep-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '케이블 해머 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-hammer-curl.png',
      'gif': 'assets/biceps/cable-hammer-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },
    {
      'title': '케이블 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-preacher-curl.png',
      'gif': 'assets/biceps/cable-preacher-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },

    {
      'title': '머신 바이셉 컬',
      'subtitle': '이두',
      'image': 'assets/biceps/machine-bicep-curl.png',
      'gif': 'assets/biceps/machine-bicep-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '이두',
    },

    //전완
    {
      'title': '덤벨 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/dumbbell-wrist-curl.png',
      'gif': 'assets/forearm/dumbbell-wrist-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },
    {
      'title': '덤벨 리버스 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/dumbbell-reverse-wrist-curl.png',
      'gif': 'assets/forearm/dumbbell-reverse-wrist-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },
    {
      'title': '바벨 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/barbell-wrist-curl.png',
      'gif': 'assets/forearm/barbell-wrist-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },
    {
      'title': '바벨 리버스 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/barbell-reverse-wrist-curl.png',
      'gif': 'assets/forearm/barbell-reverse-wrist-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },
    {
      'title': '리스트 롤러',
      'subtitle': '전완, 어깨',
      'image': 'assets/forearm/wrist-roller.png',
      'gif': 'assets/forearm/wrist-roller.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },
    {
      'title': '비하인드 백 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/behind-the-back-wrist-curl.png',
      'gif': 'assets/forearm/behind-the-back-wrist-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '전완',
    },

    //복근
    {
      'title': '크런치',
      'subtitle': '복근',
      'image': 'assets/abs/crunch.png',
      'gif': 'assets/abs/crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '디클라인 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/decline-crunch.png',
      'gif': 'assets/abs/decline-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '바이시클 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/bicycle-crunch.png',
      'gif': 'assets/abs/bicycle-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '보수 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/bosu-crunch.png',
      'gif': 'assets/abs/bosu-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '리버스 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/reverse-crunch.png',
      'gif': 'assets/abs/reverse-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '사이드 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/side-crunch.png',
      'gif': 'assets/abs/side-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },

    {
      'title': '싯 업(윗몸일으키기)',
      'subtitle': '복근',
      'image': 'assets/abs/sit-up.png',
      'gif': 'assets/abs/sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '디클라인 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/decline-sit-up.png',
      'gif': 'assets/abs/decline-sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '버터플라이 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/butterfly-sit-up.png',
      'gif': 'assets/abs/butterfly-sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '엘보우 투 니 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/elbow-to-knee-sit-up.png',
      'gif': 'assets/abs/elbow-to-knee-sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '레이즈드 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/raised-sit-up.png',
      'gif': 'assets/abs/raised-sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': 'V 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/v-sit-up.png',
      'gif': 'assets/abs/v-sit-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },

    {
      'title': '케이블 시티드 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/cable-seated-crunch.png',
      'gif': 'assets/abs/cable-seated-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '케이블 스탠딩 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/cable-standing-crunch.png',
      'gif': 'assets/abs/cable-standing-crunch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    
    {
      'title': '중량 러시안 트위스트',
      'subtitle': '복근',
      'image': 'assets/abs/weighted-russian-twist.png',
      'gif': 'assets/abs/weighted-russian-twist.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '케이블 트위스트',
      'subtitle': '복근',
      'image': 'assets/abs/cable-twist.png',
      'gif': 'assets/abs/cable-twist.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },

    {
      'title': '레그 레이즈',
      'subtitle': '복근',
      'image': 'assets/abs/leg-raise.png',
      'gif': 'assets/abs/leg-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '행잉 레그 레이즈',
      'subtitle': '복근',
      'image': 'assets/abs/hanging-leg-raise.png',
      'gif': 'assets/abs/hanging-leg-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '캡틴 체어 니 레이즈',
      'subtitle': '복근, 삼두',
      'image': 'assets/abs/captains-chair-knee-raise.png',
      'gif': 'assets/abs/captains-chair-knee-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '토즈 투 바',
      'subtitle': '복근, 어깨',
      'image': 'assets/abs/toes-to-bar.png',
      'gif': 'assets/abs/toes-to-bar.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },

    {
      'title': '플랭크',
      'subtitle': '복근',
      'image': 'assets/abs/plank.png',
      'gif': 'assets/abs/plank.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },
    {
      'title': '사이드 플랭크',
      'subtitle': '복근, 둔근',
      'image': 'assets/abs/side-plank.png',
      'gif': 'assets/abs/side-plank.png',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '복근',
    },

    //둔근
    {
      'title': '스테퍼',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/stepper.png',
      'gif': 'assets/glutes/stepper.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '스텝 업',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/step-up.png',
      'gif': 'assets/glutes/step-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },

    {
      'title': '케이블 킥 백',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/cable-kickback.png',
      'gif': 'assets/glutes/cable-kickback.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-thrust.png',
      'gif': 'assets/glutes/hip-thrust.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '싱글 레그 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/single-leg-hip-thrust.png',
      'gif': 'assets/glutes/single-leg-hip-thrust.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '바벨 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/barbell-hip-thrust.png',
      'gif': 'assets/glutes/barbell-hip-thrust.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '엘리베이트 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/elevated-hip-thrust.png',
      'gif': 'assets/glutes/elevated-hip-thrust.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '케이블 풀 쓰루',
      'subtitle': '둔근, 등',
      'image': 'assets/glutes/cable-pull-through.png',
      'gif': 'assets/glutes/cable-pull-through.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    
    {
      'title': '힙 브릿지',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-bridge.png',
      'gif': 'assets/glutes/hip-bridge.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '밴드 힙 어브덕션',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/band-hip-abduction.png',
      'gif': 'assets/glutes/band-hip-abduction.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '프로그 펌프',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/frog-pump.png',
      'gif': 'assets/glutes/frog-pump.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '머신 힙 어브덕션(아웃 싸이)',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-abduction-machine.png',
      'gif': 'assets/glutes/hip-abduction-machine.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },
    {
      'title': '리버스 디피싯 런지',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/reverse-deficit-lunge.png',
      'gif': 'assets/glutes/reverse-deficit-lunge.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '둔근',
    },

    //대퇴사두
    {
      'title': '스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/squat.png',
      'gif': 'assets/quadriceps/squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '스플릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/split-squat.png',
      'gif': 'assets/quadriceps/split-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-squat.png',
      'gif': 'assets/quadriceps/barbell-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '바벨 프론트 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-front-squat.png',
      'gif': 'assets/quadriceps/barbell-front-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '바벨 핵 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-hack-squat.png',
      'gif': 'assets/quadriceps/barbell-hack-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스플릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-split-squat.png',
      'gif': 'assets/quadriceps/barbell-split-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스모 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-sumo-squat.png',
      'gif': 'assets/quadriceps/barbell-sumo-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '덤벨 고블릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/dumbbell-goblet-squat.png',
      'gif': 'assets/quadriceps/dumbbell-goblet-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '불가리안 스플릿 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/bulgarian-split-squat.png',
      'gif': 'assets/quadriceps/bulgarian-split-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '싸이클리스트 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/cyclist-squat.png',
      'gif': 'assets/quadriceps/cyclist-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '머신 핵 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/machine-hack-squat.png',
      'gif': 'assets/quadriceps/machine-hack-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '피스톨 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/pistol-squat.png',
      'gif': 'assets/quadriceps/pistol-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },

    {
      'title': '레그 익스텐션',
      'subtitle': '대퇴사두',
      'image': 'assets/quadriceps/leg-extension.png',
      'gif': 'assets/quadriceps/leg-extension.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '레그 프레스',
      'subtitle': '대퇴사두, 종아리',
      'image': 'assets/quadriceps/leg-press.png',
      'gif': 'assets/quadriceps/leg-press.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },

    {
      'title': '런지',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/lunge.png',
      'gif': 'assets/quadriceps/lunge.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '스미스 머신 런지',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/smith-machine-lunge.png',
      'gif': 'assets/quadriceps/smith-machine-lunge.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },

    {
      'title': '바벨 스내치',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-snatch.png',
      'gif': 'assets/quadriceps/barbell-snatch.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '케틀벨 스내치',
      'subtitle': '대퇴사두, 어깨',
      'image': 'assets/quadriceps/barbell-split-squat.png',
      'gif': 'assets/quadriceps/barbell-split-squat.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    
    {
      'title': '버피',
      'subtitle': '대퇴사두, 전신',
      'image': 'assets/quadriceps/burpee.png',
      'gif': 'assets/quadriceps/burpee.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '스쿼트 버피',
      'subtitle': '대퇴사두, 전신',
      'image': 'assets/quadriceps/squat-burpee.png',
      'gif': 'assets/quadriceps/squat-burpee.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '싸이클',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/cycle.png',
      'gif': 'assets/quadriceps/cycle.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '일립티컬 머신',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/elliptical-machine.png',
      'gif': 'assets/quadriceps/elliptical-machine.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },

    {
      'title': '트레드밀',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/treadmill-running.png',
      'gif': 'assets/quadriceps/treadmill-running.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '인클라인 트레드밀',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/incline-treadmill.png',
      'gif': 'assets/quadriceps/incline-treadmill.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },
    {
      'title': '스텝 업',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/weighted-step-up.png',
      'gif': 'assets/quadriceps/weighted-step-up.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '대퇴사두',
    },

    //햄스트링
    {
      'title': '데드리프트(바벨 데드리프트)',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-deadlift.png',
      'gif': 'assets/hamstring/barbell-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '바벨 굿모닝',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-good-morning.png',
      'gif': 'assets/hamstring/barbell-good-morning.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '바벨 루마니안 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-romanian-deadlift.png',
      'gif': 'assets/hamstring/barbell-romanian-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '디피싯 데드리프트',
      'subtitle': '햄스트링, 대퇴사두',
      'image': 'assets/hamstring/deficit-deadlift.png',
      'gif': 'assets/hamstring/deficit-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '덤벨 루마니안 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/dumbbell-romanian-deadlift.png',
      'gif': 'assets/hamstring/dumbbell-romanian-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '케틀벨 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/kettlebell-deadlift.png',
      'gif': 'assets/hamstring/kettlebell-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '스미스 머신 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/smith-machine-deadlift.png',
      'gif': 'assets/hamstring/smith-machine-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '스티프 레그 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/stiff-leg-deadlift.png',
      'gif': 'assets/hamstring/stiff-leg-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '스모 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/sumo-deadlift.png',
      'gif': 'assets/hamstring/sumo-deadlift.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },

    {
      'title': '레그 컬',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/leg-curl.png',
      'gif': 'assets/hamstring/leg-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '라잉 레그 컬',
      'subtitle': '햄스트링, 종아리',
      'image': 'assets/hamstring/lying-leg-curl.png',
      'gif': 'assets/hamstring/lying-leg-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '시티드 레그 컬',
      'subtitle': '햄스트링, 종아리',
      'image': 'assets/hamstring/seated-leg-curl.png',
      'gif': 'assets/hamstring/seated-leg-curl.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },
    {
      'title': '글루트 햄 레이즈',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/glute-ham-raise.png',
      'gif': 'assets/hamstring/glute-ham-raise.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },

    {
      'title': '로잉 머신',
      'subtitle': '햄스트링, 대퇴사두',
      'image': 'assets/hamstring/rowing-machine.png',
      'gif': 'assets/hamstring/rowing-machine.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },

    {
      'title': '케틀벨 스윙',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/kettlebell-swing.png',
      'gif': 'assets/hamstring/kettlebell-swing.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },

    {
      'title': '박스 점프',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/box-jump.png',
      'gif': 'assets/hamstring/box-jump.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '햄스트링',
    },

    //승모
    {
      'title': '바벨 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/barbell-shrug.png',
      'gif': 'assets/trapezius/barbell-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },
    {
      'title': '바벨 비하인드 백 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/behind-back-shrug.png',
      'gif': 'assets/trapezius/behind-back-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },
    {
      'title': '바벨 오버헤드 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/overhead-shrug.png',
      'gif': 'assets/trapezius/overhead-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },

    {
      'title': '덤벨 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/dumbbell-shrug.png',
      'gif': 'assets/trapezius/dumbbell-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },

    {
      'title': '랫 풀 다운 리버스 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/lat-pulldown-reverse-shrug.png',
      'gif': 'assets/trapezius/lat-pulldown-reverse-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },

    {
      'title': '케이블 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/cable-shrug.png',
      'gif': 'assets/trapezius/cable-shrug.gif',
      'tip':"""   """,
      'preparation':"""   """,
      'movement':"""   """,
      'breathing':"""  """,
      'precautions':"""   """,
      'category': '승모',
    },

    //종아리
    {
      'title': '카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/calf-raise.png',
      'gif': 'assets/calf/calf-raise.gif',
      'tip':"""매끈한 종아리를 만들기 위한 운동이에요""",
      'preparation':"""밟고 올라갈 수 있는 물체를 준비해주세요
물체 위에 두 발을 앞꿈치로 올라서 주세요
어깨너비로 다리를 벌려주세요""",
      'movement':"""최대한 높이 발뒤꿈치를 올려 종아리 근육을 수축해 주세요
무게 저항을 버티며 발뒤꿈치가 땅에 닿지 않게 멈춰주세요""",
      'breathing':"""다리를 올릴 때 숨을 내쉬고, 다리를 내릴 때 숨을 들이쉬세요""",
      'precautions':"""중심을 잡기 어려울 때는 벽이나 물체를 손으로 짚어주세요""",
      'category': '종아리',
    },
    {
      'title': '스탠딩 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/standing-calf-raise.png',
      'gif': 'assets/calf/standing-calf-raise.gif',
      'tip':"""내려갔다가 올라올때 중간에서 한번 멈췄다가 끝까지 올려보세요""",
      'preparation':"""어깨 위에 무게를 위치시키고, 양손으로 머신을 잡고 받침대 위에 서세요""",
      'movement':"""종아리의 힘을 이용하여 몸 전체를 위로 들어올리세요
종아리의 자극을 유지하면서 천천히 몸을 내려 시작 자세로 돌아오세요""",
      'breathing':"""다리를 올릴 때 숨을 내쉬고, 다리를 내릴 때 숨을 들이쉬세요""",
      'precautions':"""허리가 꺾이지 않도록 가슴을 펴고, 코어에 힘을 주세요""",
      'category': '종아리',
    },
    {
      'title': '덤벨 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/dumbbell-calf-raise.png',
      'gif': 'assets/calf/dumbbell-calf-raise.gif',
      'tip':"""움직임을 서두르지 마세요
      천천히 발뒤꿈치를 땅에서 들어올리면서 종아리를 위쪽으로 조이세요
      그런 다음 발뒤꿈치를 천천히 아래로 내리세요""",
      'preparation':"""발을 어깨 너비로 벌리고 발가락을 곧게 펴거나 약간 바깥쪽으로 놓으세요""",
      'movement':"""숨을 내쉬면서 양쪽 발의 볼을 아래로 밀어내며 복부 근육이 수축되고 등이 곧게 펴지도록 하여 발뒤꿈치를 바닥에서 천천히 들어 올리세요
종아리가 완전히 수축되고 발의 공으로 균형을 잡을 때 잠시 멈추세요
숨을 들이쉬면서 점차적으로 발뒤꿈치를 바닥에 내려 시작 위치로 낮추어 동작 전반에 걸쳐 제어력을 유지시키세요""",
      'breathing':"""다리를 밀 때 숨을 내쉬고, 다리를 당길 때 숨을 들이쉬세요""",
      'precautions':"""흔들리거나 앞으로 기대지 마세요""",
      'category': '종아리',
    },
    {
      'title': '덤벨 시티드 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/dumbbell-seated-calf-raise.png',
      'gif': 'assets/calf/dumbbell-seated-calf-raise.gif',
      'tip':"""발뒤꿈치를 최대한 높이 들어 발의 볼을 밀어내세요""",
      'preparation':"""등을 곧게 펴고 덤벨이 무릎에서 미끄러지지 않도록 단단히 잡으세요""",
      'movement':"""두 발의 볼을 아래로 눌러 발뒤꿈치를 바닥에서 천천히 들어올리면서 덤벨이 흔들리지 않게 유지하세요
종아리가 최대한 높아졌을 때 잠시 멈췄다가 천천히 발뒤꿈치를 낮추어 시작 위치로 돌아갑니다
원하는 반복 횟수만큼 이 동작을 반복하여 운동 전반에 걸쳐 덤벨과 균형을 제어할 수 있도록 하세요""",
      'breathing':"""다리를 밀 때 숨을 내쉬고, 다리를 당길 때 숨을 들이쉬세요""",
      'precautions':""" 동작의 가장 아래쪽에서 발뒤꿈치를 바닥에서 튕겨내면 근력보다는 운동량을 사용하게 되어 운동의 효과를 감소시킬수 있으니 주의하세요 
      항상 발뒤꿈치를 천천히 그리고 통제된 방식으로 낮추세요""",
      'category': '종아리',
    },
    {
      'title': '레그 프레스 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/leg-press-calf-raise.png',
      'gif': 'assets/calf/leg-press-calf-raise.gif',
      'tip':"""카프 레이즈를 할 때 가능한 다리를 곧게 하세요""",
      'preparation':"""몸을 머신 중앙에 위치시키고, 발판 하단에 발을 올려주세요
다다리는 어깨너비보다 좁게 벌려주세요
가슴을 펴고, 허리는 살짝 아치를 만들어 주세요""",
      'movement':"""발뒤꿈치를 밀어 종아리 근육을 수축해 주세요.
무게 저항을 버티며 천천히 시작 자세로 돌아와 주세요""",
      'breathing':"""다리를 밀 때 숨을 내쉬고, 다리를 당길 때 숨을 들이쉬세요""",
      'precautions':"""무릎이 벌어지지 않게 조심해 주세요
허리가 꺾이지 않도록 가슴을 펴고, 코어에 힘을 주세요""",
      'category': '종아리',
    },
    {
      'title': '시티드 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/seated-calf-raise.png',
      'gif': 'assets/calf/seated-calf-raise.gif',
      'tip':"""바닥에 뒷꿈치가 닿으면 근육의 긴장이 풀어지므로 주의하세요""",
      'preparation':"""머신에 앉아서 앞쪽에 솟아있는 손잡이를 양손으로 잡고, 등을 아치형으로 유지하세요
      발의 간격은 엉덩이 너비 정도로 벌리고, 무릎을 패드밑에 밀착시킨 상태로 발바닥의 앞부분만 발판에 걸치세요
      호흡을 내쉬며 뒤꿈치를 가능한 한 높이 올린후 호흡을 들이쉬며 뒷꿈치가 바닥에 닿기 직전까지 충분히 내려주세요""",
      'movement':"""발 받침대 위에 양발을 올리고 머신에 앉으세요
발 뒷꿈치를 최대한의 높이로 천천히 올려주세요 이때 종아리 근육을 쥐어짠다는 느낌으로 잠깐 멈춰주세요
천천히 발 뒷꿈치를 내려 시작 자세로 돌아오세요""",
      'breathing':"""다리를 밀 때 숨을 내쉬고, 다리를 당길 때 숨을 들이쉬세요""",
      'precautions':"""무릎이 벌어지지 않게 조심해 주세요
허리가 꺾이지 않도록 가슴을 펴고, 코어에 힘을 주세요""",
      'category': '종아리',
    },
    {
      'title': '스미스 머신 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/smith-machine-calf-raise.png',
      'gif': 'assets/calf/smith-machine-calf-raise.gif',
      'tip':"""카프 레이즈를 할 때 가능한 다리를 곧게 하세요""",
      'preparation':"""스텝 박스 위에 두 발을 앞꿈치로 올라서 주세요
어깨너비보다 넓게 바벨을 잡고, 승모근에 올려주세요
어깨너비로 다리를 벌려주세요""",
      'movement':"""최대한 높이 발뒤꿈치를 올려 종아리 근육을 수축해 주세요
무게 저항을 버티며 발뒤꿈치가 땅에 닿지 않게 멈춰주세요""",
      'breathing':"""다리를 올릴 때 숨을 내쉬고, 다리를 내릴 때 숨을 들이쉬세요""",
      'precautions':"""발뒤꿈치를 많이 내려 중심이 흔들리지 않도록 조심해 주세요
상체가 흔들리지 않도록 코어에 힘을 주세요""",
      'category': '종아리',
    },

    {
      'title': '줄넘기',
      'subtitle': '종아리, 이두',
      'image': 'assets/calf/jump-rope.png',
      'gif': 'assets/calf/jump-rope.gif',
      'tip':"""몸을 똑바로 세우고 일정한 속도로 점프하세요""",
      'preparation':"""양발을 함께 모으고 줄을 뒤에 둔 채로""",
      'movement':"""발을 고정하고 손잡이를 잡은 상태로 앉으세요
다리를 쭉 펴면서 손잡이를 몸쪽으로 당기세요
팔이 완전히 펴지지 않도록 조절하고 복부 힘을 유지하세요""",
      'breathing':"""일정하게 숨을 들이마시고 내쉰다""",
      'precautions':"""뛰는 동안 발목에 무리가 가지 않도록 부드럽게 착지하세요""",
      'category': '종아리',
    },
  ];