final List<Map<String, String>> items = [
    //등
    {
      'title': '랫 풀 다운',
      'subtitle': '등, 이두',
      'image': 'assets/back/lat-pulldown.png',
      'gif':'assets/back/lat-pulldown.gif',
      'tip': """랫 풀 다운은 등 상부 근육에 집중적으로 작용하여 세밀한 근육 발달을 위해 효과적입니다. 자세 교정과 근력 향상에 도움이 됩니다.""",
      'description': """랫 풀 다운 머신 앞에 앉아 손잡이에 손을 넓게 잡아주세요.
몸을 뒤로 젖혀 앉고, 발은 바닥에 고정하세요.
팔을 완전히 뻗은 상태에서 시작합니다.""",
      'precautions': """적절한 중량을 선택하세요. 
운동 중 불편함을 느끼면 즉시 중단하세요. 
상체를 고정하고 팔만 움직이세요.""",
      'category': '등',
    },
    {
      'title': '원 암 랫 풀 다운',
      'subtitle': '등, 이두',
      'image': 'assets/back/one-arm-lat-pulldown.png',
      'gif':'assets/back/one-arm-lat-pulldown.gif',
      'category': '등',
    },
    {
      'title': '클로스 그립 랫 풀 다운',
      'subtitle': '등, 어깨',
      'image': 'assets/back/close-grip-lat-pulldown.png',
      'gif': 'assets/back/close-grip-lat-pulldown.gif',
      'category': '등',
    },

    {
      'title': '케이블 스트레이트 암 풀 다운',
      'subtitle': '등, 어깨',
      'image': 'assets/back/cable-straight-arm-pulldown.png',
      'gif': 'assets/back/cable-straight-arm-pulldown.gif',
      'category': '등',
    },

    {
      'title': '풀 업',
      'subtitle': '등, 이두',
      'image': 'assets/back/pull-up.png',
      'gif': 'assets/back/pull-up.gif',
      'category': '등',
    },
    {
      'title': '중량 풀업',
      'subtitle': '등, 이두',
      'image': 'assets/back/weighted-pull-up.png',
      'gif': 'assets/back/weighted-pull-up.png',
      'category': '등',
    },
    {
      'title': '어시스티드 머신 풀업',
      'subtitle': '등, 이두',
      'image': 'assets/back/assisted-pull-up.png',
      'gif': 'assets/back/assisted-pull-up.gif',
      'category': '등',
    },
    {
      'title': '밴드 풀 업',
      'subtitle': '등, 이두',
      'image': 'assets/back/band-pull-up.png',
      'gif': 'assets/back/band-pull-up.gif',
      'category': '등',
    },

    {
      'title': '친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/chin-up.png',
      'gif': 'assets/back/chin-up.gif',
      'category': '등',
    },
    {
      'title': '중량 친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/weighted-chin-up.png',
      'gif': 'assets/back/weighted-chin-up.gif',
      'category': '등',
    },
    {
      'title': '밴드 친 업',
      'subtitle': '등, 전완',
      'image': 'assets/back/band-chin-up.png',
      'gif': 'assets/back/band-chin-up.gif',
      'category': '등',
    },

    {
      'title': '케이블 시티드 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/cable-seated-row.png',
      'gif': 'assets/back/cable-seated-row.gif',
      'category': '등',
    },
    {
      'title': '바벨 로우(벤트 오버 바벨 로우)',
      'subtitle': '등, 이두',
      'image': 'assets/back/barbell-row.png',
      'gif': 'assets/back/barbell-row.gif',
      'category': '등',
    },
    {
      'title': '펜들레이 로우',
      'subtitle': '등',
      'image': 'assets/back/pendlay-row.png',
      'gif': 'assets/back/pendlay-row.gif',
      'category': '등',
    },
    {
      'title': '티 바 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/t-bar-row.png',
      'gif': 'assets/back/t-bar-row.gif',
      'category': '등',
    },
    {
      'title': '인버티드 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/inverted-row.png',
      'gif': 'assets/back/inverted-row.gif',
      'category': '등',
    },

    {
      'title': '덤벨 로우(벤트 오버 덤벨 로우)',
      'subtitle': '등, 이두',
      'image': 'assets/back/dumbbell-row.png',
      'gif': 'assets/back/dumbbell-row.gif',
      'category': '등',
    },
    {
      'title': '원 암 덤벨 로우',
      'subtitle': '등, 이두',
      'image': 'assets/back/one-arm-dumbbell-row.png',
      'gif': 'assets/back/one-arm-dumbbell-row.gif',
      'category': '등',
    },
    {
      'title': '덤벨 리어 델트 로우',
      'subtitle': '등, 어깨',
      'image': 'assets/back/dumbbell-rear-delt-row.png',
      'gif': 'assets/back/dumbbell-rear-delt-row.gif',
      'category': '등',
    },

    {
      'title': '백 익스텐션',
      'subtitle': '등, 둔근',
      'image': 'assets/back/back-extension.png',
      'gif': 'assets/back/back-extension.gif',
      'category': '등',
    },

    //가슴
    {
      'title': '바벨 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-bench-press.png',
      'gif': 'assets/chest/barbell-bench-press.gif',
      'category': '가슴',
    },
    {
      'title': '바벨 인클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-incline-bench-press.png',
      'gif': 'assets/chest/barbell-incline-bench-press.gif',
      'category': '가슴',
    },
    {
      'title': '바벨 디클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/barbell-decline-bench-press.png',
      'gif': 'assets/chest/barbell-decline-bench-press.gif',
      'category': '가슴',
    },

    {
      'title': '덤벨 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-bench-press.png',
      'gif': 'assets/chest/dumbbell-bench-press.gif',
      'category': '가슴',
    },
    {
      'title': '덤벨 인클라인 벤치 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-incline-bench-press.png',
      'gif': 'assets/chest/dumbbell-incline-bench-press.gif',
      'category': '가슴',
    },

    {
      'title': '머신 체스트 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/machine-chest-press.png',
      'gif': 'assets/chest/machine-chest-press.gif',
      'category': '가슴',
    },
    {
      'title': '랜드마인 체스트 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/landmine-chest-press.png',
      'gif': 'assets/chest/landmine-chest-press.gif',
      'category': '가슴',
    },
    {
      'title': '덤벨 헥스 프레스',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/dumbbell-hex-press.png',
      'gif': 'assets/chest/dumbbell-hex-press.gif',
      'category': '가슴',
    },
    {
      'title': '스벤드 프레스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/svend-press.png',
      'gif': 'assets/chest/svend-press.gif',
      'category': '가슴',
    },

    {
      'title': '케이블 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-fly.png',
      'gif': 'assets/chest/cable-fly.gif',
      'category': '가슴',
    },
    {
      'title': '케이블 하이 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-high-fly.png',
      'gif': 'assets/chest/cable-high-fly.gif',
      'category': '가슴',
    },
    {
      'title': '케이블 로우 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/cable-low-fly.png',
      'gif': 'assets/chest/cable-low-fly.gif',
      'category': '가슴',
    },
    {
      'title': '케이블 인클라인 벤치 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/incline-cable-fly.png',
      'gif': 'assets/chest/incline-cable-fly.gif',
      'category': '가슴',
    },
    {
      'title': '케이블 디클라인 벤치 플라이',
      'subtitle': '가슴, 어깨',
      'image': 'assets/chest/decline-cable-fly.png',
      'gif': 'assets/chest/decline-cable-fly.gif',
      'category': '가슴',
    },

    {
      'title': '푸시 업',
      'subtitle': '가슴, 어깨, 삼두',
      'image': 'assets/chest/push-up.png',
      'gif': 'assets/chest/push-up.gif',
      'category': '가슴',
    },
    {
      'title': '중량 푸시 업',
      'subtitle': '가슴, 어깨, 삼두',
      'image': 'assets/chest/weighted-push-up.png',
      'gif': 'assets/chest/weighted-push-up.gif',
      'category': '가슴',
    },

    {
      'title': '바벨 풀 오버',
      'subtitle': '가슴, 등',
      'image': 'assets/chest/barbell-pullover.png',
      'gif': 'assets/chest/barbell-pullover.gif',
      'category': '가슴',
    },
    {
      'title': '덤벨 풀 오버',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/dumbbell-pullover.png',
      'gif': 'assets/chest/dumbbell-pullover.gif',
      'category': '가슴',
    },

    {
      'title': '팩 덱 플라이(머신 플라이)',
      'subtitle': '가슴',
      'image': 'assets/chest/pec-deck-fly.png',
      'gif': 'assets/chest/pec-deck-fly.gif',
      'category': '가슴',
    },

    {
      'title': '체스트 딥스',
      'subtitle': '가슴, 삼두',
      'image': 'assets/chest/chest-dip.png',
      'gif': 'assets/chest/chest-dip.gif',
      'category': '가슴',
    },
    
    //어깨
    {
      'title': '바벨 숄더 프레스(밀리터리 프레스, 오버헤드 프레스)',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/military-press.png',
      'gif': 'assets/shoulder/military-press.gif',
      'category': '어깨',
    },
    {
      'title': '덤벨 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/dumbbell-front-raise.png',
      'gif': 'assets/shoulder/dumbbell-front-raise.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/cable-front-raise.png',
      'gif': 'assets/shoulder/cable-front-raise.gif',
      'category': '어깨',
    },
    {
      'title': '플레이트 프론트 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/plate-front-raise.png',
      'gif': 'assets/shoulder/plate-front-raise.gif',
      'category': '어깨',
    },
    {
      'title': '아놀드 덤벨 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/arnold-press.png',
      'gif': 'assets/shoulder/arnold-press.gif',
      'category': '어깨',
    },
    {
      'title': '시티드 덤벨 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/dumbbell-shoulder-press.png',
      'gif': 'assets/shoulder/dumbbell-shoulder-press.gif',
      'category': '어깨',
    },
    {
      'title': '머신 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/machine-shoulder-press.png',
      'gif': 'assets/shoulder/machine-shoulder-press.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 숄더 프레스',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/cable-shoulder-press.png',
      'gif': 'assets/shoulder/cable-shoulder-press.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 업라이트 로우',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/cable-upright-row.png',
      'gif': 'assets/shoulder/cable-upright-row.gif',
      'category': '어깨',
    },
    {
      'title': '바벨 업라이트 로우',
      'subtitle': '어깨, 승모',
      'image': 'assets/shoulder/barbell-upright-row.png',
      'gif': 'assets/shoulder/barbell-upright-row.gif',
      'category': '어깨',
    },
    

    {
      'title': '덤벨 레터럴 레이즈(사이드 레터럴 레이즈)',
      'subtitle': '어깨',
      'image': 'assets/shoulder/dumbbell-lateral-raise.png',
      'gif': 'assets/shoulder/dumbbell-lateral-raise.gif',
      'category': '어깨',
    },
    {
      'title': '머신 레터럴 레이즈',
      'subtitle': '어깨',
      'image': 'assets/shoulder/machine-lateral-raise.png',
      'gif': 'assets/shoulder/machine-lateral-raise.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 레터럴 레이즈',
      'subtitle': '어깨, 전완',
      'image': 'assets/shoulder/cable-lateral-raise.png',
      'gif': 'assets/shoulder/cable-lateral-raise.gif',
      'category': '어깨',
    },
    {
      'title': '덤벨 인클라인 Y 레이즈',
      'subtitle': '어깨, 승모',
      'image': 'assets/shoulder/dumbbell-incline-y-raise.png',
      'gif': 'assets/shoulder/dumbbell-incline-y-raise.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 Y 레이즈',
      'subtitle': '어깨, 삼두',
      'image': 'assets/shoulder/cable-y-raise.png',
      'gif': 'assets/shoulder/cable-y-raise.gif',
      'category': '어깨',
    },
    

    {
      'title': '덤벨 리어 델트 레이즈(벤트 오버 레터럴 레이즈)',
      'subtitle': '어깨, 등',
      'image': 'assets/shoulder/dumbbell-rear-delt-raise.png',
      'gif': 'assets/shoulder/dumbbell-rear-delt-raise.gif',
      'category': '어깨',
    },
    {
      'title': '머신 리버스 플라이(팩 덱 리어 델트, 머신 리어 델트 플라이)',
      'subtitle': '어깨, 등',
      'image': 'assets/shoulder/machine-reverse-fly.png',
      'gif': 'assets/shoulder/machine-reverse-fly.gif',
      'category': '어깨',
    },
    {
      'title': '케이블 페이스 풀',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/cable-face-pull.png',
      'gif': 'assets/shoulder/cable-face-pull.gif',
      'category': '어깨',
    },
    {
      'title': '밴드 페이스 풀',
      'subtitle': '어깨, 이두',
      'image': 'assets/shoulder/banded-face-pull.png',
      'gif': 'assets/shoulder/banded-face-pull.gif',
      'category': '어깨',
    },

    {
      'title': '클린 앤 저크',
      'subtitle': '어깨, 대퇴사두',
      'image': 'assets/shoulder/clean-and-jerk.png',
      'gif': 'assets/shoulder/clean-and-jerk.gif',
      'category': '어깨',
    },

    //삼두
    {
      'title': '클로즈 그립 벤치 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/close-grip-bench-press.png',
      'gif': 'assets/triceps/close-grip-bench-press.gif',
      'category': '삼두',
    },
    {
      'title': '클로즈 그립 덤벨 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/close-grip-dumbbell-press.png',
      'gif': 'assets/triceps/close-grip-dumbbell-press.gif',
      'category': '삼두',
    },
    {
      'title': '덤벨 테이트 프레스',
      'subtitle': '삼두, 가슴',
      'image': 'assets/triceps/dumbbell-tate-press.png',
      'gif': 'assets/triceps/dumbbell-tate-press.gif',
      'category': '삼두',
    },

    {
      'title': '딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/tricep-dips.png',
      'gif': 'assets/triceps/tricep-dips.gif',
      'category': '삼두',
    },
    {
      'title': '중량 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/weighted-dips.png',
      'gif': 'assets/triceps/weighted-dips.gif',
      'category': '삼두',
    },
    {
      'title': '머신 어시스티드 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/machine-assisted-dips.png',
      'gif': 'assets/triceps/machine-assisted-dips.gif',
      'category': '삼두',
    },
    {
      'title': '벤치 딥스',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/bench-dips.png',
      'gif': 'assets/triceps/bench-dips.gif',
      'category': '삼두',
    },

    {
      'title': '덤벨 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/dumbbell-tricep-extension.png',
      'gif': 'assets/triceps/dumbbell-tricep-extension.gif',
      'category': '삼두',
    },
    {
      'title': '원 암 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/one-arm-tricep-extension.png',
      'gif': 'assets/triceps/one-arm-tricep-extension.gif',
      'category': '삼두',
    },
    {
      'title': '덤벨 라잉 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/dumbbell-lying-tricep-extension.png',
      'gif': 'assets/triceps/dumbbell-lying-tricep-extension.gif',
      'category': '삼두',
    },
    {
      'title': '머신 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/machine-tricep-extension.png',
      'gif': 'assets/triceps/machine-tricep-extension.gif',
      'category': '삼두',
    },

    {
      'title': '바벨 라잉 트라이셉 익스텐션(스컬크러셔)',
      'subtitle': '삼두, 전완',
      'image': 'assets/triceps/barbell-lying-tricep-extension.png',
      'gif': 'assets/triceps/barbell-lying-tricep-extension.gif',
      'category': '삼두',
    },
    {
      'title': '바벨 인클라인 트라이셉 익스텐션(스컬크러셔)',
      'subtitle': '삼두',
      'image': 'assets/triceps/barbell-incline-tricep-extension.png',
      'gif': 'assets/triceps/barbell-incline-tricep-extension.gif',
      'category': '삼두',
    },

    {
      'title': '케이블 오버헤드 트라이셉 익스텐션',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-overhead-tricep-extension.png',
      'gif': 'assets/triceps/cable-overhead-tricep-extension.gif',
      'category': '삼두',
    },

    {
      'title': '케이블 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-tricep-pushdown.png',
      'gif': 'assets/triceps/cable-tricep-pushdown.gif',
      'category': '삼두',
    },
    {
      'title': '케이블 로프 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-rope-tricep-pushdown.png',
      'gif': 'assets/triceps/cable-rope-tricep-pushdown.gif',
      'category': '삼두',
    },
    {
      'title': '케이블 리버스그립 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-reverse-grip-pushdown.png',
      'gif': 'assets/triceps/cable-reverse-grip-pushdown.gif',
      'category': '삼두',
    },
    {
      'title': '케이블 V바 트라이셉 푸시다운',
      'subtitle': '삼두',
      'image': 'assets/triceps/v-bar-tricep-pushdown.png',
      'gif': 'assets/triceps/v-bar-tricep-pushdown.gif',
      'category': '삼두',
    },

    {
      'title': '덤벨 트라이셉 킥 백',
      'subtitle': '삼두, 어깨',
      'image': 'assets/triceps/dumbbell-tricep-kickback.png',
      'gif': 'assets/triceps/dumbbell-tricep-kickback.gif',
      'category': '삼두',
    },
    {
      'title': '케이블 트라이셉 킥 백',
      'subtitle': '삼두',
      'image': 'assets/triceps/cable-tricep-kickback.png',
      'gif': 'assets/triceps/cable-tricep-kickback.gif',
      'category': '삼두',
    },
    
    //이두
    {
      'title': '컨센트레이션 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/concentration-curl.png',
      'gif': 'assets/biceps/concentration-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤벨 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-biceps-curl.png',
      'gif': 'assets/biceps/dumbbell-biceps-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤벨 해머 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/hammer-curl.png',
      'gif': 'assets/biceps/hammer-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤벨 인클라인 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-incline-curl.png',
      'gif': 'assets/biceps/dumbbell-incline-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤벨 인클라인 해머 컬',
      'subtitle': '이두',
      'image': 'assets/biceps/dumbbell-incline-hammer-curl.png',
      'gif': 'assets/biceps/dumbbell-incline-hammer-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤벨 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/dumbbell-preacher-curl.png',
      'gif': 'assets/biceps/dumbbell-preacher-curl.gif',
      'category': '이두',
    },
    {
      'title': '덤밸 조트맨 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/zottman-curl.png',
      'gif': 'assets/biceps/zottman-curl.gif',
      'category': '이두',
    },

    {
      'title': '바벨 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-curl.png',
      'gif': 'assets/biceps/barbell-curl.gif',
      'category': '이두',
    },
    {
      'title': '바벨 클로즈 그립 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-close-grip-curl.png',
      'gif': 'assets/biceps/barbell-close-grip-curl.gif',
      'category': '이두',
    },
    {
      'title': '바벨 리버스 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-reverse-curl.png',
      'gif': 'assets/biceps/barbell-reverse-curl.gif',
      'category': '이두',
    },
    {
      'title': '바벨 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/barbell-preacher-curl.png',
      'gif': 'assets/biceps/barbell-preacher-curl.gif',
      'category': '이두',
    },
    {
      'title': '바벨 드래그 컬',
      'subtitle': '이두, 어깨',
      'image': 'assets/biceps/drag-curl.png',
      'gif': 'assets/biceps/drag-curl.gif',
      'category': '이두',
    },
    {
      'title': '스파이더 바벨 컬',
      'subtitle': '이두, 어깨',
      'image': 'assets/biceps/spider-barbell-curl.png',
      'gif': 'assets/biceps/spider-barbell-curl.gif',
      'category': '이두',
    },

    {
      'title': '이지 바 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-bicep-curl.png',
      'gif': 'assets/biceps/ez-bar-bicep-curl.gif',
      'category': '이두',
    },
    {
      'title': '이지 바 리버스 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-reverse-curl.png',
      'gif': 'assets/biceps/ez-bar-reverse-curl.gif',
      'category': '이두',
    },
    {
      'title': '이지 바 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/ez-bar-preacher-curl.png',
      'gif': 'assets/biceps/ez-bar-preacher-curl.gif',
      'category': '이두',
    },

    {
      'title': '케이블 바이셉 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-bicep-curl.png',
      'gif': 'assets/biceps/cable-bicep-curl.gif',
      'category': '이두',
    },
    {
      'title': '케이블 해머 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-hammer-curl.png',
      'gif': 'assets/biceps/cable-hammer-curl.gif',
      'category': '이두',
    },
    {
      'title': '케이블 프리쳐 컬',
      'subtitle': '이두, 전완',
      'image': 'assets/biceps/cable-preacher-curl.png',
      'gif': 'assets/biceps/cable-preacher-curl.gif',
      'category': '이두',
    },

    {
      'title': '머신 바이셉 컬',
      'subtitle': '이두',
      'image': 'assets/biceps/machine-bicep-curl.png',
      'gif': 'assets/biceps/machine-bicep-curl.gif',
      'category': '이두',
    },

    //전완
    {
      'title': '덤벨 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/dumbbell-wrist-curl.png',
      'gif': 'assets/forearm/dumbbell-wrist-curl.gif',
      'category': '전완',
    },
    {
      'title': '덤벨 리버스 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/dumbbell-reverse-wrist-curl.png',
      'gif': 'assets/forearm/dumbbell-reverse-wrist-curl.gif',
      'category': '전완',
    },
    {
      'title': '바벨 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/barbell-wrist-curl.png',
      'gif': 'assets/forearm/barbell-wrist-curl.gif',
      'category': '전완',
    },
    {
      'title': '바벨 리버스 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/barbell-reverse-wrist-curl.png',
      'gif': 'assets/forearm/barbell-reverse-wrist-curl.gif',
      'category': '전완',
    },
    {
      'title': '리스트 롤러',
      'subtitle': '전완, 어깨',
      'image': 'assets/forearm/wrist-roller.png',
      'gif': 'assets/forearm/wrist-roller.gif',
      'category': '전완',
    },
    {
      'title': '비하인드 백 리스트 컬',
      'subtitle': '전완',
      'image': 'assets/forearm/behind-the-back-wrist-curl.png',
      'gif': 'assets/forearm/behind-the-back-wrist-curl.gif',
      'category': '전완',
    },

    //복근
    {
      'title': '크런치',
      'subtitle': '복근',
      'image': 'assets/abs/crunch.png',
      'gif': 'assets/abs/crunch.gif',
      'category': '복근',
    },
    {
      'title': '디클라인 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/decline-crunch.png',
      'gif': 'assets/abs/decline-crunch.gif',
      'category': '복근',
    },
    {
      'title': '바이시클 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/bicycle-crunch.png',
      'gif': 'assets/abs/bicycle-crunch.gif',
      'category': '복근',
    },
    {
      'title': '보수 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/bosu-crunch.png',
      'gif': 'assets/abs/bosu-crunch.gif',
      'category': '복근',
    },
    {
      'title': '리버스 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/reverse-crunch.png',
      'gif': 'assets/abs/reverse-crunch.gif',
      'category': '복근',
    },
    {
      'title': '사이드 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/side-crunch.png',
      'gif': 'assets/abs/side-crunch.gif',
      'category': '복근',
    },

    {
      'title': '싯 업(윗몸일으키기)',
      'subtitle': '복근',
      'image': 'assets/abs/sit-up.png',
      'gif': 'assets/abs/sit-up.gif',
      'category': '복근',
    },
    {
      'title': '디클라인 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/decline-sit-up.png',
      'gif': 'assets/abs/decline-sit-up.gif',
      'category': '복근',
    },
    {
      'title': '버터플라이 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/butterfly-sit-up.png',
      'gif': 'assets/abs/butterfly-sit-up.gif',
      'category': '복근',
    },
    {
      'title': '엘보우 투 니 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/elbow-to-knee-sit-up.png',
      'gif': 'assets/abs/elbow-to-knee-sit-up.gif',
      'category': '복근',
    },
    {
      'title': '레이즈드 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/raised-sit-up.png',
      'gif': 'assets/abs/raised-sit-up.gif',
      'category': '복근',
    },
    {
      'title': 'V 싯 업',
      'subtitle': '복근',
      'image': 'assets/abs/v-sit-up.png',
      'gif': 'assets/abs/v-sit-up.gif',
      'category': '복근',
    },

    {
      'title': '케이블 시티드 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/cable-seated-crunch.png',
      'gif': 'assets/abs/cable-seated-crunch.gif',
      'category': '복근',
    },
    {
      'title': '케이블 스탠딩 크런치',
      'subtitle': '복근',
      'image': 'assets/abs/cable-standing-crunch.png',
      'gif': 'assets/abs/cable-standing-crunch.gif',
      'category': '복근',
    },
    
    {
      'title': '중량 러시안 트위스트',
      'subtitle': '복근',
      'image': 'assets/abs/weighted-russian-twist.png',
      'gif': 'assets/abs/weighted-russian-twist.gif',
      'category': '복근',
    },
    {
      'title': '케이블 트위스트',
      'subtitle': '복근',
      'image': 'assets/abs/cable-twist.png',
      'gif': 'assets/abs/cable-twist.gif',
      'category': '복근',
    },

    {
      'title': '레그 레이즈',
      'subtitle': '복근',
      'image': 'assets/abs/leg-raise.png',
      'gif': 'assets/abs/leg-raise.gif',
      'category': '복근',
    },
    {
      'title': '행잉 레그 레이즈',
      'subtitle': '복근',
      'image': 'assets/abs/hanging-leg-raise.png',
      'gif': 'assets/abs/hanging-leg-raise.gif',
      'category': '복근',
    },
    {
      'title': '캡틴 체어 니 레이즈',
      'subtitle': '복근, 삼두',
      'image': 'assets/abs/captains-chair-knee-raise.png',
      'gif': 'assets/abs/captains-chair-knee-raise.gif',
      'category': '복근',
    },
    {
      'title': '토즈 투 바',
      'subtitle': '복근, 어깨',
      'image': 'assets/abs/toes-to-bar.png',
      'gif': 'assets/abs/toes-to-bar.gif',
      'category': '복근',
    },

    {
      'title': '플랭크',
      'subtitle': '복근',
      'image': 'assets/abs/plank.png',
      'gif': 'assets/abs/plank.gif',
      'category': '복근',
    },
    {
      'title': '사이드 플랭크',
      'subtitle': '복근, 둔근',
      'image': 'assets/abs/side-plank.png',
      'gif': 'assets/abs/side-plank.png',
      'category': '복근',
    },

    //둔근
    {
      'title': '스테퍼',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/stepper.png',
      'gif': 'assets/glutes/stepper.gif',
      'category': '둔근',
    },
    {
      'title': '스텝 업',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/step-up.png',
      'gif': 'assets/glutes/step-up.gif',
      'category': '둔근',
    },

    {
      'title': '케이블 킥 백',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/cable-kickback.png',
      'gif': 'assets/glutes/cable-kickback.gif',
      'category': '둔근',
    },
    {
      'title': '힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-thrust.png',
      'gif': 'assets/glutes/hip-thrust.gif',
      'category': '둔근',
    },
    {
      'title': '싱글 레그 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/single-leg-hip-thrust.png',
      'gif': 'assets/glutes/single-leg-hip-thrust.gif',
      'category': '둔근',
    },
    {
      'title': '바벨 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/barbell-hip-thrust.png',
      'gif': 'assets/glutes/barbell-hip-thrust.gif',
      'category': '둔근',
    },
    {
      'title': '엘리베이트 힙 쓰러스트',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/elevated-hip-thrust.png',
      'gif': 'assets/glutes/elevated-hip-thrust.gif',
      'category': '둔근',
    },
    {
      'title': '케이블 풀 쓰루',
      'subtitle': '둔근, 등',
      'image': 'assets/glutes/cable-pull-through.png',
      'gif': 'assets/glutes/cable-pull-through.gif',
      'category': '둔근',
    },
    
    {
      'title': '힙 브릿지',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-bridge.png',
      'gif': 'assets/glutes/hip-bridge.gif',
      'category': '둔근',
    },
    {
      'title': '밴드 힙 어브덕션',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/band-hip-abduction.png',
      'gif': 'assets/glutes/band-hip-abduction.gif',
      'category': '둔근',
    },
    {
      'title': '프로그 펌프',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/frog-pump.png',
      'gif': 'assets/glutes/frog-pump.gif',
      'category': '둔근',
    },
    {
      'title': '머신 힙 어브덕션(아웃 싸이)',
      'subtitle': '둔근, 햄스트링',
      'image': 'assets/glutes/hip-abduction-machine.png',
      'gif': 'assets/glutes/hip-abduction-machine.gif',
      'category': '둔근',
    },
    {
      'title': '리버스 디피싯 런지',
      'subtitle': '둔근, 대퇴사두',
      'image': 'assets/glutes/reverse-deficit-lunge.png',
      'gif': 'assets/glutes/reverse-deficit-lunge.gif',
      'category': '둔근',
    },

    //대퇴사두
    {
      'title': '스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/squat.png',
      'gif': 'assets/quadriceps/squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '스플릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/split-squat.png',
      'gif': 'assets/quadriceps/split-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-squat.png',
      'gif': 'assets/quadriceps/barbell-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '바벨 프론트 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-front-squat.png',
      'gif': 'assets/quadriceps/barbell-front-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '바벨 핵 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-hack-squat.png',
      'gif': 'assets/quadriceps/barbell-hack-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스플릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-split-squat.png',
      'gif': 'assets/quadriceps/barbell-split-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '바벨 스모 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/barbell-sumo-squat.png',
      'gif': 'assets/quadriceps/barbell-sumo-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '덤벨 고블릿 스쿼트',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/dumbbell-goblet-squat.png',
      'gif': 'assets/quadriceps/dumbbell-goblet-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '불가리안 스플릿 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/bulgarian-split-squat.png',
      'gif': 'assets/quadriceps/bulgarian-split-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '싸이클리스트 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/cyclist-squat.png',
      'gif': 'assets/quadriceps/cyclist-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '머신 핵 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/machine-hack-squat.png',
      'gif': 'assets/quadriceps/machine-hack-squat.gif',
      'category': '대퇴사두',
    },
    {
      'title': '피스톨 스쿼트',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/pistol-squat.png',
      'gif': 'assets/quadriceps/pistol-squat.gif',
      'category': '대퇴사두',
    },

    {
      'title': '레그 익스텐션',
      'subtitle': '대퇴사두',
      'image': 'assets/quadriceps/leg-extension.png',
      'gif': 'assets/quadriceps/leg-extension.gif',
      'category': '대퇴사두',
    },
    {
      'title': '레그 프레스',
      'subtitle': '대퇴사두, 종아리',
      'image': 'assets/quadriceps/leg-press.png',
      'gif': 'assets/quadriceps/leg-press.gif',
      'category': '대퇴사두',
    },

    {
      'title': '런지',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/lunge.png',
      'gif': 'assets/quadriceps/lunge.gif',
      'category': '대퇴사두',
    },
    {
      'title': '스미스 머신 런지',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/smith-machine-lunge.png',
      'gif': 'assets/quadriceps/smith-machine-lunge.gif',
      'category': '대퇴사두',
    },

    {
      'title': '바벨 스내치',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/barbell-snatch.png',
      'gif': 'assets/quadriceps/barbell-snatch.gif',
      'category': '대퇴사두',
    },
    {
      'title': '케틀벨 스내치',
      'subtitle': '대퇴사두, 어깨',
      'image': 'assets/quadriceps/barbell-split-squat.png',
      'gif': 'assets/quadriceps/barbell-split-squat.gif',
      'category': '대퇴사두',
    },
    
    {
      'title': '버피',
      'subtitle': '대퇴사두, 전신',
      'image': 'assets/quadriceps/burpee.png',
      'gif': 'assets/quadriceps/burpee.gif',
      'category': '대퇴사두',
    },
    {
      'title': '스쿼트 버피',
      'subtitle': '대퇴사두, 전신',
      'image': 'assets/quadriceps/squat-burpee.png',
      'gif': 'assets/quadriceps/squat-burpee.gif',
      'category': '대퇴사두',
    },
    {
      'title': '싸이클',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/cycle.png',
      'gif': 'assets/quadriceps/cycle.gif',
      'category': '대퇴사두',
    },
    {
      'title': '일립티컬 머신',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/elliptical-machine.png',
      'gif': 'assets/quadriceps/elliptical-machine.gif',
      'category': '대퇴사두',
    },

    {
      'title': '트레드밀',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/treadmill-running.png',
      'gif': 'assets/quadriceps/treadmill-running.gif',
      'category': '대퇴사두',
    },
    {
      'title': '인클라인 트레드밀',
      'subtitle': '대퇴사두, 햄스트링',
      'image': 'assets/quadriceps/incline-treadmill.png',
      'gif': 'assets/quadriceps/incline-treadmill.gif',
      'category': '대퇴사두',
    },
    {
      'title': '스텝 업',
      'subtitle': '대퇴사두, 둔근',
      'image': 'assets/quadriceps/weighted-step-up.png',
      'gif': 'assets/quadriceps/weighted-step-up.gif',
      'category': '대퇴사두',
    },

    //햄스트링
    {
      'title': '데드리프트(바벨 데드리프트)',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-deadlift.png',
      'gif': 'assets/hamstring/barbell-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '바벨 굿모닝',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-good-morning.png',
      'gif': 'assets/hamstring/barbell-good-morning.gif',
      'category': '햄스트링',
    },
    {
      'title': '바벨 루마니안 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/barbell-romanian-deadlift.png',
      'gif': 'assets/hamstring/barbell-romanian-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '디피싯 데드리프트',
      'subtitle': '햄스트링, 대퇴사두',
      'image': 'assets/hamstring/deficit-deadlift.png',
      'gif': 'assets/hamstring/deficit-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '덤벨 루마니안 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/dumbbell-romanian-deadlift.png',
      'gif': 'assets/hamstring/dumbbell-romanian-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '케틀벨 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/kettlebell-deadlift.png',
      'gif': 'assets/hamstring/kettlebell-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '스미스 머신 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/smith-machine-deadlift.png',
      'gif': 'assets/hamstring/smith-machine-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '스티프 레그 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/stiff-leg-deadlift.png',
      'gif': 'assets/hamstring/stiff-leg-deadlift.gif',
      'category': '햄스트링',
    },
    {
      'title': '스모 데드리프트',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/sumo-deadlift.png',
      'gif': 'assets/hamstring/sumo-deadlift.gif',
      'category': '햄스트링',
    },

    {
      'title': '레그 컬',
      'subtitle': '햄스트링, 등',
      'image': 'assets/hamstring/leg-curl.png',
      'gif': 'assets/hamstring/leg-curl.gif',
      'category': '햄스트링',
    },
    {
      'title': '라잉 레그 컬',
      'subtitle': '햄스트링, 종아리',
      'image': 'assets/hamstring/lying-leg-curl.png',
      'gif': 'assets/hamstring/lying-leg-curl.gif',
      'category': '햄스트링',
    },
    {
      'title': '시티드 레그 컬',
      'subtitle': '햄스트링, 종아리',
      'image': 'assets/hamstring/seated-leg-curl.png',
      'gif': 'assets/hamstring/seated-leg-curl.gif',
      'category': '햄스트링',
    },
    {
      'title': '글루트 햄 레이즈',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/glute-ham-raise.png',
      'gif': 'assets/hamstring/glute-ham-raise.gif',
      'category': '햄스트링',
    },

    {
      'title': '로잉 머신',
      'subtitle': '햄스트링, 대퇴사두',
      'image': 'assets/hamstring/rowing-machine.png',
      'gif': 'assets/hamstring/rowing-machine.gif',
      'category': '햄스트링',
    },

    {
      'title': '케틀벨 스윙',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/kettlebell-swing.png',
      'gif': 'assets/hamstring/kettlebell-swing.gif',
      'category': '햄스트링',
    },

    {
      'title': '박스 점프',
      'subtitle': '햄스트링, 둔근',
      'image': 'assets/hamstring/box-jump.png',
      'gif': 'assets/hamstring/box-jump.gif',
      'category': '햄스트링',
    },

    //승모
    {
      'title': '바벨 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/barbell-shrug.png',
      'gif': 'assets/trapezius/barbell-shrug.gif',
      'category': '승모',
    },
    {
      'title': '바벨 비하인드 백 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/behind-back-shrug.png',
      'gif': 'assets/trapezius/behind-back-shrug.gif',
      'category': '승모',
    },
    {
      'title': '바벨 오버헤드 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/overhead-shrug.png',
      'gif': 'assets/trapezius/overhead-shrug.gif',
      'category': '승모',
    },

    {
      'title': '덤벨 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/dumbbell-shrug.png',
      'gif': 'assets/trapezius/dumbbell-shrug.gif',
      'category': '승모',
    },

    {
      'title': '랫 풀 다운 리버스 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/lat-pulldown-reverse-shrug.png',
      'gif': 'assets/trapezius/lat-pulldown-reverse-shrug.gif',
      'category': '승모',
    },

    {
      'title': '케이블 슈러그',
      'subtitle': '승모',
      'image': 'assets/trapezius/cable-shrug.png',
      'gif': 'assets/trapezius/cable-shrug.gif',
      'category': '승모',
    },

    //종아리
    {
      'title': '카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/calf-raise.png',
      'gif': 'assets/calf/calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '스탠딩 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/standing-calf-raise.png',
      'gif': 'assets/calf/standing-calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '덤벨 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/dumbbell-calf-raise.png',
      'gif': 'assets/calf/dumbbell-calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '덤벨 시티드 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/dumbbell-seated-calf-raise.png',
      'gif': 'assets/calf/dumbbell-seated-calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '레그 프레스 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/leg-press-calf-raise.png',
      'gif': 'assets/calf/leg-press-calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '시티드 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/seated-calf-raise.png',
      'gif': 'assets/calf/seated-calf-raise.gif',
      'category': '종아리',
    },
    {
      'title': '스미스 머신 카프 레이즈',
      'subtitle': '종아리',
      'image': 'assets/calf/smith-machine-calf-raise.png',
      'gif': 'assets/calf/smith-machine-calf-raise.gif',
      'category': '종아리',
    },

    {
      'title': '줄넘기',
      'subtitle': '종아리, 이두',
      'image': 'assets/calf/jump-rope.png',
      'gif': 'assets/calf/jump-rope.gif',
      'category': '종아리',
    },
  ];